apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: casewebportal
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: casewebportal
    spec:
      containers:
      - name: casewebportal
        image: case/webportal:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6100
